# Generated by Django 3.2.7 on 2021-10-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
