# Generated by Django 5.0.1 on 2024-02-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                    ("X", "Prefer not to say"),
                ],
                default="X",
                max_length=1,
            ),
        ),
    ]
