# Generated by Django 3.2.7 on 2021-09-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.BooleanField(choices=[(False, 'مرد'), (True, 'زن')], default=True),
        ),
    ]
