# Generated by Django 3.2.7 on 2021-10-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_discountcode_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
