# Generated by Django 5.0.1 on 2024-02-02 18:22

import django.core.validators
from django.db import migrations, models

import customers.models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customer_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pics/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    ),
                    customers.models.validate_image_size,
                ],
            ),
        ),
    ]
