# Generated by Django 3.2.7 on 2021-10-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('آماده ارسال', 'آماده ارسال'), ('فرستاده شد', 'فرستاده شد'), ('دریافت شد', 'دریافت شد')], default='آماده ارسال', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
