# Generated by Django 3.2.7 on 2021-09-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ref_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='ref_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('ready_to_deliver', 'ready_to_deliver'), ('delivering', 'delivering'), ('delivered', 'delivered')], default='ready_to_deliver', max_length=20),
        ),
    ]
