# Generated by Django 3.2.7 on 2021-09-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210927_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='delivered_date',
            new_name='date',
        ),
    ]
