# Generated by Django 3.2.7 on 2021-09-27 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_delivered_date_orderhistory_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='status',
            new_name='delivery_status',
        ),
    ]
