# Generated by Django 3.2.7 on 2021-09-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_status_orderhistory_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='ordered_date',
        ),
    ]
