# Generated by Django 3.2.7 on 2021-09-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderhistory_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='delivery_status',
            field=models.CharField(choices=[('آماده ارسال', 'آماده ارسال'), ('فرستاده شد', 'فرستاده شد'), ('دریافت شد', 'دریافت شد')], default='آماده ارسال', max_length=20),
        ),
    ]
