# Generated by Django 3.2.7 on 2021-09-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(default='بازار', max_length=200),
        ),
    ]
